title: SurfsUp🌊SDK Documentation
logo: /Assets/sdk_logo.png
description: Custom map making documentation for the video game SurfsUp
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
